name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - run: dart pub global activate flutter_distributor
      - run: flutter pub get
      - if: matrix.os == 'macos-14'
        run: |
          npm install -g appdmg
          flutter_distributor release --name ${{ matrix.os }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: dist/*/*

